const mongoose = require("mongoose");
mongoose.Promise = global.Promise;
const db = {};
db.mongoose = mongoose;
db.url = "mongodb+srv://djellali:12345678esi@cluster0.rrjvt.mongodb.net/myFirstDatabase?retryWrites=true&w=majority";
db.User = require("./user.model")(mongoose);
db.Product = require("./product.model")(mongoose);
db.Order = require("./order.model")(mongoose);
db.Categorie = require("./categorie.model")(mongoose);
module.exports = db;